### ISSUE TITLE
Can't backup components using npx sb-mig backup components -all

### ISSUE THREAD

**Issue by SebbeJohansson** [sb-mig/sb-mig#188]
**Describe the bug**
Running `npx sb-mig backup components -all` results in nothing happening

**To Reproduce**
1. Create new empty project.
2. run npm install --global sb-mig.
3. Add values to .env.
4. Run `npx sb-mig backup components -all``
5. ???
6. Nothing.

**Expected behavior**
I expect that a backup of my components will end up in the project somewhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/5083273/183501966-2a4d0555-e324-42a8-a26f-1bd29c9d83fb.png)

**Additional context**
I am running node 16.16.0.

**Comment by SebbeJohansson** [comment]
I have also tested with the latest version of node.

**Comment by marckraw** [comment]
Hi there @SebbeJohansson sorry for not responding for a long time, didnt get notifictation. Had to properly set it up ;) 

Regards the problem, will take a look at that, there were some changes recently to support `commonjs` and `esm` aswell, so probably that's the problem. For which version of `sb-mig` that errors occurs ?

**Comment by SebbeJohansson** [comment]
Hi. In the latest version!

**Comment by SebbeJohansson** [comment]
Hi! Any idea on if/when this will be fixed? Just tried it again and I still cant use sb-mig :(

**Comment by marckraw** [comment]
@SebbeJohansson hey! will try to focus on that this week, had to much other stuff on my plate. 
In the meantime you can try `@beta` version, becasue i was pushing some changes to that for some time. Just to double check it it happens in beta aswell.

**Comment by marckraw** [comment]
oh, and one thing i noticed just now is that you used `-all` not `--all` modifier, so the proper command should look like
```
npx sb-mig backup components --all
```

**Comment by marckraw** [comment]
@SebbeJohansson if u run 
```
npx sb-mig debug
```

can you show me what is `sb-mig` displaying ? ?

**Comment by marckraw** [comment]
also, if u have 
```
"type": "module" 
```

in you `package.json`
you have to define your `storyblok.config.js` with esm syntax:
```
export default {
    oauthToken: process.env.STORYBLOK_OAUTH_TOKEN,
    spaceId: process.env.STORYBLOK_SPACE_ID,
    accessToken: process.env.STORYBLOK_ACCESS_TOKEN
}
```

and that could also be a thing. Sorry for late response, and late ideas, christmas time :D

**Comment by marckraw** [comment]
@SebbeJohansson 
Ooooook couple things

I've fixed bunch of stuff in `@beta` and there was a problem with dynamic import of `storyblok.config.js` specifically on windows, which is now fixed (so it will properly import your file)

So, i strongly recommend install `sb-mig` globally with 
```
npm install sb-mig@4.1.0-beta.31
```

and use this version

or install it in your project
```
npm install sb-mig@4.1.0-beta.31
```

and create a script for backup in your `package.json`
```
"backup": "sb-mig backup components --all
```

If every env is correct, so it points to proper storyblok space, it should backup all components :)

Here is also reproduction repo i've created and tested on windows, so it should work after you change envs to your own.

https://github.com/sb-mig/sb-mig-issue-188

**Comment by SebbeJohansson** [comment]
Still not working :(
![image](https://user-images.githubusercontent.com/5083273/210108667-6f5edc80-685e-4986-9be9-0c9dc057749e.png)

If i run your reproduction repo I get this:
![image](https://user-images.githubusercontent.com/5083273/210109018-a2affe50-6db1-464b-adfb-088fa61a1102.png)

npx sb-mig debug doesn't work either.
![image](https://user-images.githubusercontent.com/5083273/210109280-07ce88e9-edac-4d22-9dfb-34b47b2009a0.png)
If I run it in your reproduction repo I get this:
![image](https://user-images.githubusercontent.com/5083273/210109372-cd95ec83-9650-4be4-925e-d2cc0096ebc9.png)

When you are developing and running this, what version of node are you running? I am using latest 16.

Sorry for late reply. I haven't been feeling well so been away for a few days.

**Comment by marckraw** [comment]
using LTS version, so 18.12.1

**Comment by marckraw** [comment]
@SebbeJohansson so maybe try using 18, its possible that its related to that (sb-mig is created with native esm in mind, which maybe is not available in node 16). And since node 18 is now LTS. than everyone should migrate to it.

**Comment by marckraw** [comment]
@SebbeJohansson 
yup, i'm 100% sure, that its related to node version, tried with `node 16.17.1`
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/8228270/210136731-3a433034-a20f-49fa-a01d-5bbcf5560c70.png">

**Comment by SebbeJohansson** [comment]
> @SebbeJohansson so maybe try using 18, its possible that its related to that (sb-mig is created with native esm in mind, which maybe is not available in node 16). And since node 18 is now LTS. than everyone should migrate to it.

Not that everyone can migrate, but I get your point. 18 being LTS is fairly new so I mainly stay to 16. 

I have tested with 18 and it seems to work :) Thanks.

**Comment by SebbeJohansson** [comment]
@marckraw Might be a good idea to add a notice in the repo about the 18 requirement!

**Comment by marckraw** [comment]
good point, will do :)

**Comment by marckraw** [comment]
@SebbeJohansson can you double check version `4.1.0-beta.33`. (with node 16) Just released it with typescript target to be `esm2017`, so maybe this version will have backward compatibility for node16 :) not  tested though, so let me know :)

**Comment by SebbeJohansson** [comment]
@marckraw Thanks for trying, but sadly it didn't work.
![image](https://user-images.githubusercontent.com/5083273/210820875-0d09838c-7354-4d51-b629-3ebccf576ddf.png)

I say, just force people to use lts. that is fine I think!

**Comment by marckraw** [comment]
@SebbeJohansson daaaaamn, yeah, i've added note in readme with requirement
